from geometry import Environment, Source
from converter import _convert_design_region_to_cells, _stamp_grid_onto_design_region, _convert_sources_to_cells, _convert_receivers_to_cells, _stamp_source_walls_to_design_region
import ceviche
import ceviche.sources
import numpy as np
from typing import List, Dict

"""
Okay. we are finally done with the converter module. Now, we should go ahead and write the simulation module next. 

thus far the user is able to:
--> Create a rod
--> Create a source
--> create receiver
--> create grid
--> create design region

now, we need to:
--> initialize these objects using converter functions in the correct order so that they exist in ceviche terms pre simulation implementations [DONE]
--> simulate e-fields using ceviche as our solver [DONE]
--> take measurements from receivers  
--> insert sources into the design region [DONE]

later, there will also be some agentic functions we need to implement, such as sampling rods / adding noise to the rods etc, but those are not the highest priority yet. 

there will also be a visualization module we need to build later but that can also wait for now.

what do you think of this plan? i did not realize how much work was already done, i think the converter module was by far the hardest part. the rest of the work hopefully should be relatively easy. what do you think?
"""


def initialize_environment(env: Environment) -> Environment: 
    """
    The function initializes the Ceviche objects for simulation purposes. 
    Converts each physical object defined by user into corresponding array equivalents.
    Alters the design region in place in the correct order of objects. 
    Saves converted arrays inside the environment. 

    Post initialization, _canvas serves as the design region and is accessible to the user. _canvas stores all rods in a grid format as needed. source._mask and receiver._mask are also saved for future reference. 

    Inputs:
    --> env [Environment]: User defined environment storing all objects, to be initialized. 

    Returns:
    --> env [Environment]: Returns the altered environment along with converted objects. 

    Note that the function does not need to return the environment since it is altered in place and objects are stored in it anyways. We return the object for ease of use and testing. 
    """
    # 01. _convert_design_region_to_cells(): We need the canvas to exist first
    _convert_design_region_to_cells(env=env)

    # 02. _stamp_grid_onto_design_region()
    _stamp_grid_onto_design_region(env=env)

    # 03. Generate source masks for Ceviche
    _convert_sources_to_cells(env=env)
    # Put the source walls in place right after
    _stamp_source_walls_to_design_region(env=env)
    
    # 04. Generate receiver masks for Ceviche
    _convert_receivers_to_cells(env=env)

    return env


def simulate_ez_fields_per_source(env: Environment) -> Dict[int, np.ndarray]: 
    """
    The function simulates the E_z fields generated by each individual source inserted into the design region. 

    Inputs:
    --> env [Environment]: Environment object to be simulated

    Returns:
    --> ez_fields [Dict[int, np.ndarray]]: Dictionary containing [index, Ez field] associated with each of the sources.
    """
    ez_fields = {}
    num_pml_cells = env.design_region.num_pml_cells

    for source in env.sources:
        # Convert source frequency to angular frequency 
        omega = 2 * np.pi * source.frequency # [radians/second]

        # Create FDFD simulation object at given physical properties
        simulation = ceviche.fdfd_ez(omega=omega, dL=env.design_region.resolution, eps_r=env.design_region._canvas, npml=[num_pml_cells, num_pml_cells])

        # Define source vector containing the location and direction for source
        source_vector = np.zeros_like(env.design_region._canvas, dtype=complex)
        source_vector[source._mask == 1] = 1e3  # bumped amplitude

        # Solve for E_z field
        hx, hy, ez = simulation.solve(source_vector)
        ez_fields[source.index] = ez

    return ez_fields


def simulate_total_ez_field(env: Environment) -> np.ndarray:
    """
    The function simulates the cumulative E_z field generated by all sources inserted into the design region. 

    Inputs:
    --> env [Environment]: Environment object to be simulated

    Returns:
    --> ez_field [np.ndarray]: E_z field array containing the superposition of all fields generated by independent sources. 
    """
    # If there are no sources in design region, return 0s everywhere
    if env.sources == []:
        return np.zeros_like(env.design_region._canvas, dtype=complex)
    
    # Otherwise, calculate the total Ez at all cells
    ez_fields = simulate_ez_fields_per_source(env=env)
    return sum(ez_fields.values())


def measure_field_intensity_per_receiver_per_source(env: Environment) -> Dict[int, Dict[int, float]]: 
    """
    Calculates the individual field intensity contributions of all sources at set receiver locations (all receivers defined onto the design region). 

    The field intensity at a given receiver is defined as E_z ** 2 at its location.

    Input:
    --> env [Environment]: Environment object storing the receivers and sources

    Returns:
    --> field_intensities [Dict[int, Dict[int, float]]]: Saves each source contribution at a given receiver location in the form of {receiver_index: {source_index: intensity}}.
    """
    # Generate Ez fields per source
    ez_fields_per_source = simulate_ez_fields_per_source(env=env)
    field_intensities = {}

    # At each receiver location, get the Ez field generated by all sources
    for receiver in env.receivers:
        # Create temporary list to store contributions from all sources
        intensities_at_this_receiver = {}
        # Calculate contributions from all sources
        for source_index, ez in ez_fields_per_source.items():
            intensity = np.sum(np.abs(ez) ** 2 * receiver._mask)
            intensities_at_this_receiver[source_index] = intensity
        # Save individual contributions 
        field_intensities[receiver.index] = intensities_at_this_receiver
    
    return field_intensities


def measure_total_intensity_per_receiver(env: Environment) -> Dict[int, float]:
    """
    Calculates the total field intensity at a given receiver location. 

    The field intensity at a given receiver is defined as E_z ** 2 at its location.

    Input: 
    --> env [Environment]: Environment object storing the receivers

    Returns: 
    --> total_intensities [Dict[int, float]]: Dictionary storing the total field intensity at each receiver, in the form of {receiver_index: total_field_intensity}.
    """
    total_intensities = {}

    # Get field intensities with source information 
    field_intensities = measure_field_intensity_per_receiver_per_source(env=env)

    # Sum over all contributions from sources to get total field intensity
    for receiver_index, field_values in field_intensities.items():
        total_intensities[receiver_index] = sum(field_values.values())

    return total_intensities